language: node_js
node_js:
- '6'
- '4'
notifications:
  email: false
  slack:
    secure: NtUctcQymDloMrq7J2qkap3wCZkKyTC11+cTg96QY4P/1eQjOuWqsVy56EYnkERsD/8aCmr81VVzovviymBXjL3YSyywXD+fglj3Ai9X/SifX4Eue6P9Qy9QowQx0rRxIDu77y0Rko8fCpZ554NFSn6KpdmGcpFfSYn3dlLiyGK9LfbYx69sT8RidLJxg8n2ujIj29IMQpfka2JIJCCT8Z4Z1R65Amj8sHxPURue/Nv5rG83LjOI0RWxrx91MJBG6bm9tKiySjGbDVrOKJK/M0ORxEdwjDSooYRCzGYbEZdqMQ0k2lYt5txJwcw5uBQnR2TjPFexeACOkofim0GsxP/yPiit3j0uunu2IbYwzGwtvg54P1hkjI0oiUmpXyHyCf59F8JkCiVtuINhjatxVTRxUCNkNPVsVuQ8xVSs8XL3bt5uDlbHzlzX4A8iparVAEfrJKvlMeycIJzIb8Cp66DAhBzfVWn1AcYF1U9Ff3JKqHHVOElDFqBtc7VgwhbKz15LUhLNGIMSZN/SwN2gFFWUL7x+fu0j0l2xIk1wI2Rho2yZWkE0XlgZJgy+Tlsg0buvsPf0VBzat/GoPVZNWLSkmBxbNhQ1NxHMghuVs9THIvQJwAM9oFLPmcqpyIpTxwKsC8fnXTwZo327Gyl/H/1Njz8nmZoRF9srf8OA7SA=
